# Generated by Django 4.1.2 on 2024-05-15 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='predict_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=10)),
                ('education', models.CharField(max_length=10)),
                ('marital_status', models.CharField(max_length=10)),
                ('age', models.CharField(max_length=10)),
                ('limit', models.CharField(max_length=10)),
                ('repay_april', models.CharField(max_length=10)),
                ('repay_may', models.CharField(max_length=10)),
                ('repay_june', models.CharField(max_length=10)),
                ('repay_july', models.CharField(max_length=10)),
                ('repay_aug', models.CharField(max_length=10)),
                ('repay_sep', models.CharField(max_length=10)),
                ('bill_april', models.CharField(max_length=10)),
                ('bill_may', models.CharField(max_length=10)),
                ('bill_june', models.CharField(max_length=10)),
                ('bill_july', models.CharField(max_length=10)),
                ('bill_aug', models.CharField(max_length=10)),
                ('bill_sep', models.CharField(max_length=10)),
                ('prev_april', models.CharField(max_length=10)),
                ('prev_may', models.CharField(max_length=10)),
                ('prev_june', models.CharField(max_length=10)),
                ('prev_july', models.CharField(max_length=10)),
                ('prev_aug', models.CharField(max_length=10)),
                ('prev_sep', models.CharField(max_length=10)),
                ('default_pay', models.CharField(max_length=10)),
            ],
        ),
    ]
